nome = str(input("n\ Entre com nome: "))
endereço = str(input("n\ Entre com endereço: "))
telefone = str(input("n\ Entre com telefone: "))
print ("\n\n\n")
print (f"\n Nome: {nome}")
print (f"\n Endereço: {endereço}")
print (f"\n Telefone: {telefone}")
print("\n")